// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<main.Task>>;

export function QuitApp():Promise<void>;

export function UpdateTask(arg1:main.Task):Promise<main.Task>;
